name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Run linting
        run: pnpm lint

  test_karma:
    runs-on: ubuntu-latest
    container: trion/ng-cli-karma
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Run Karma tests
        run: pnpm test:prod
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: "${{ github.job }}"
          path: coverage/

  sonarcloud_check:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [test_lint, test_karma]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/cache@v3
        with:
          node-version: '20.x'
          path: |-
            node_modules/
            .sonar/cache
          key: "${{ github.job }}"
      - uses: actions/download-artifact@v4
        with:
          name: test_karma
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  update_docs:
    runs-on: ubuntu-latest
    needs: [test_lint, test_karma]
    if: github.event_name == 'release' # Only update docs on tag creation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm install
      - name: Install semver
        run: pnpm add semver
      - name: Update Package Version
        run: pnpm update:package-version
      - name: Update Changelog
        run: pnpm update:changelog
      - name: Update README
        run: pnpm update:readme
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: update package version, changelog, and README"
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [update_docs]
    container: trion/ng-cli-karma
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm install
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          ng build ngx-translate-routes
          cd dist/ngx-translate-routes
          pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
